# Generated by Django 4.1.7 on 2023-03-09 05:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="followers",
            new_name="follower_users",
        ),
        migrations.RenameField(
            model_name="book",
            old_name="is_avaliable",
            new_name="is_available",
        ),
        migrations.AddField(
            model_name="follow",
            name="will_be_available_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
