# Generated by Django 4.1.7 on 2023-03-12 02:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="follow",
            name="will_be_available_date",
        ),
        migrations.AddField(
            model_name="book",
            name="will_be_available_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
