# Generated by Django 4.1.7 on 2023-03-12 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Copie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("loan_date", models.DateTimeField(auto_now_add=True)),
                ("expected_return_date", models.DateField()),
                ("delivery_date", models.DateField(blank=True, null=True)),
                (
                    "copie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="copies.copie"
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
    ]
