# Generated by Django 4.1.7 on 2023-03-08 23:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("copies", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="loan",
            unique_together={("user", "copie")},
        ),
    ]
